name: Build and Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.11'  # Escolha a versão do Node.js que você precisa

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build  # Este comando deve construir sua aplicação e colocar os arquivos necessários na pasta 'dist'

    - name: Copy dist folder to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "dist"
        target: "/path/to/your/app"

    - name: Restart Node.js application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
            if ! command -v npm &> /dev/null
            then
                echo "npm não encontrado, instalando..."
                # Comando para instalar npm
            fi
            if ! command -v pm2 &> /dev/null
            then
                echo "pm2 não encontrado, instalando..."
                npm install pm2 -g
            fi
            cd /home/personal-api.bcsgarcia.com.br/public_html/
            npm install --production
            pm2 restart all
