name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose.template.yml"
          target: "${{ secrets.PROJECT_PATH }}"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            # Login no GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Configurar variáveis de ambiente
            export GITHUB_REPOSITORY="${{ github.repository }}"
            export NODE_ENV=prod
            export PORT=${{ secrets.PORT }}
            export DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            export DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            export DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export FTP_HOST=${{ secrets.FTP_HOST }}
            export FTP_USER=${{ secrets.FTP_USER }}
            export FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}
            export FTP_CLIENT_IMAGE_PATH=${{ secrets.FTP_CLIENT_IMAGE_PATH }}
            export FTP_VIDEO_PATH=${{ secrets.FTP_VIDEO_PATH }}
            export FTP_IMAGE_PATH=${{ secrets.FTP_IMAGE_PATH }}
            export FTP_THUMBNAIL_PATH=${{ secrets.FTP_THUMBNAIL_PATH }}
            export VIDEO_BASE_PATH=${{ secrets.VIDEO_BASE_PATH }}
            export IMAGE_BASE_PATH=${{ secrets.IMAGE_BASE_PATH }}
            export THUMBNAIL_BASE_PATH=${{ secrets.THUMBNAIL_BASE_PATH }}
            export CLIENT_IMAGE_BASE_PATH=${{ secrets.CLIENT_IMAGE_BASE_PATH }}
            export CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}

            # Criar docker-compose.prod.yml a partir do template
            envsubst < docker-compose.template.yml > docker-compose.prod.yml

            # Pull da nova imagem
            docker pull ghcr.io/${{ github.repository }}:main

            # Parar e remover containers antigos
            docker-compose -f docker-compose.prod.yml down

            # Iniciar com a nova imagem
            docker-compose -f docker-compose.prod.yml up -d
